//
//  PlaceCategory+Mapbox.swift
//  LocoKit2
//
//  Created by Claude on 2026-08-10
//
//  GENERATED FILE — regenerate via Scripts/placecategory/generate_placecategory.py
//  (BIG-513). Mapbox category strings are compound comma-separated keyword
//  bundles (e.g. "hotel, motel, tourism, lodging"), not a clean taxonomy —
//  so resolution is keyword matching: first recognised token wins, tokens
//  checked in string order (Mapbox leads with the most specific term).
//  Pure history rescue: AT4 never fetches from Mapbox, so mapboxCategory
//  only exists on places migrated from AT3's Mapbox era. Table authored
//  against the observed vocabulary of a real mature DB and validated
//  against the PlaceCategory taxonomy at generation time; unmatched
//  strings resolve to nil, deliberately.
//

extension PlaceCategory {

    init?(mapboxCategory: String) {
        for token in mapboxCategory.components(separatedBy: ",") {
            let trimmed = token.trimmingCharacters(in: .whitespaces)
            if let raw = Self.mapboxKeywordMap[trimmed], let category = PlaceCategory(rawValue: raw) {
                self = category
                return
            }
        }
        return nil
    }

    static let mapboxKeywordMap: [String: String] = [
        "abm": "atm",
        "advertising": "marketing_consultant",
        "advertising agency": "marketing_consultant",
        "african food": "african_restaurant",
        "african restaurant": "african_restaurant",
        "airport": "airport",
        "airport lounge": "airport",
        "airport services": "airport",
        "airport shop": "airport",
        "american food": "american_restaurant",
        "american restaurant": "american_restaurant",
        "antique": "store",
        "apparel": "clothing_store",
        "aquarium": "aquarium",
        "art": "art_gallery",
        "art galleries": "art_gallery",
        "art gallery": "art_gallery",
        "art museum": "art_museum",
        "asian food": "asian_restaurant",
        "asian restaurant": "asian_restaurant",
        "atm": "atm",
        "attraction": "tourist_attraction",
        "auto dealer": "car_dealer",
        "auto dealership": "car_dealer",
        "auto repair": "car_repair",
        "auto sales": "car_dealer",
        "automotive dealer": "car_dealer",
        "automotive dealership": "car_dealer",
        "automotive leasing": "car_dealer",
        "automotive sales": "car_dealer",
        "bagel": "bagel_shop",
        "bakery": "bakery",
        "bank": "bank",
        "bar": "bar",
        "barber": "barber_shop",
        "bargain": "discount_store",
        "baseball": "athletic_field",
        "baseball field": "athletic_field",
        "beach": "beach",
        "beach bar": "bar",
        "bed and breakfast": "bed_and_breakfast",
        "beer": "liquor_store",
        "bicycle rental": "bicycle_store",
        "bodega": "convenience_store",
        "body shop": "car_repair",
        "book shop": "book_store",
        "bookstore": "book_store",
        "booze": "liquor_store",
        "botanical garden": "botanical_garden",
        "breakfast spot": "breakfast_restaurant",
        "brewery": "brewery",
        "bridge": "historical_landmark",
        "bubble tea": "tea_house",
        "buddhism": "buddhist_temple",
        "buddhist": "buddhist_temple",
        "burger joint": "hamburger_restaurant",
        "bus station": "bus_station",
        "bus stop": "bus_stop",
        "business": "corporate_office",
        "cafe": "cafe",
        "cajun food": "cajun_restaurant",
        "cajun restaurant": "cajun_restaurant",
        "campground": "campground",
        "camping": "campground",
        "candies": "candy_store",
        "candy": "candy_store",
        "candy store": "candy_store",
        "car dealer": "car_dealer",
        "car dealership": "car_dealer",
        "car rental": "car_rental",
        "car repair": "car_repair",
        "car sales": "car_dealer",
        "car wash": "car_wash",
        "caribbean food": "caribbean_restaurant",
        "caribbean restaurant": "caribbean_restaurant",
        "cash point": "atm",
        "cellphone": "cell_phone_store",
        "cemetery": "cemetery",
        "chair ski lift": "ski_resort",
        "charity": "non_profit_organization",
        "chicken": "chicken_restaurant",
        "chinese food": "chinese_restaurant",
        "chinese restaurant": "chinese_restaurant",
        "chocolate": "chocolate_shop",
        "chocolatier": "chocolate_shop",
        "church": "church",
        "clinic": "medical_clinic",
        "clothing": "clothing_store",
        "cocktail bar": "cocktail_bar",
        "coffee": "coffee_shop",
        "collectibles": "store",
        "college": "university",
        "college art building": "academic_department",
        "college classrooms": "academic_department",
        "college quad": "university",
        "college student center": "university",
        "computer": "electronics_store",
        "concert": "concert_hall",
        "concert hall": "concert_hall",
        "confection": "confectionery",
        "confectionery": "confectionery",
        "contractor": "general_contractor",
        "convenience": "convenience_store",
        "convenience store": "convenience_store",
        "corner store": "convenience_store",
        "coworking space": "coworking_space",
        "cuban food": "cuban_restaurant",
        "cuban restaurant": "cuban_restaurant",
        "dealership": "car_dealer",
        "decor": "home_goods_store",
        "deli": "deli",
        "dentist": "dentist",
        "department store": "department_store",
        "dim sum": "dim_sum_restaurant",
        "dim sum restaurant": "dim_sum_restaurant",
        "diner": "diner",
        "discount store": "discount_store",
        "doctor": "doctor",
        "donut": "donut_shop",
        "dumpling": "dumpling_restaurant",
        "dumpling restaurant": "dumpling_restaurant",
        "eastern european": "eastern_european_restaurant",
        "eastern european restaurant": "eastern_european_restaurant",
        "electronic": "electronics_store",
        "electronics": "electronics_store",
        "embassy": "embassy",
        "ethiopian food": "ethiopian_restaurant",
        "ethiopian restaurant": "ethiopian_restaurant",
        "event space": "event_venue",
        "events venue": "event_venue",
        "eye doctor": "doctor",
        "falafel": "falafel_restaurant",
        "falafel restaurant": "falafel_restaurant",
        "farmers market": "farmers_market",
        "fast food": "fast_food_restaurant",
        "ferry": "ferry_terminal",
        "finance": "bank",
        "fish market": "market",
        "fitness center": "fitness_center",
        "florist": "florist",
        "food and drink": "food_store",
        "food court": "food_court",
        "frame": "store",
        "framing": "store",
        "french food": "french_restaurant",
        "french restaurant": "french_restaurant",
        "fried chicken": "chicken_restaurant",
        "fruit vegetable shop": "grocery_store",
        "fuel": "gas_station",
        "furniture": "furniture_store",
        "galleries": "art_gallery",
        "gallery": "art_gallery",
        "garden": "garden",
        "gas station": "gas_station",
        "gastropub": "gastropub",
        "gift": "gift_shop",
        "gourmet": "food_store",
        "government agency": "government_office",
        "graveyard": "cemetery",
        "greek food": "greek_restaurant",
        "greek restaurant": "greek_restaurant",
        "groceries": "grocery_store",
        "grocery": "grocery_store",
        "gym": "gym",
        "hair": "hair_salon",
        "hardware": "hardware_store",
        "hike": "hiking_area",
        "hiking": "hiking_area",
        "hiking trailhead": "hiking_area",
        "historic": "historical_landmark",
        "historic site": "historical_landmark",
        "history museum": "history_museum",
        "home store": "home_goods_store",
        "hospital": "hospital",
        "hostel": "hostel",
        "hotel": "hotel",
        "hotel resort": "resort_hotel",
        "ice cream": "ice_cream_shop",
        "indian food": "indian_restaurant",
        "indian restaurant": "indian_restaurant",
        "indie theater": "movie_theater",
        "indie theatre": "movie_theater",
        "islam": "mosque",
        "israeli food": "israeli_restaurant",
        "israeli restaurant": "israeli_restaurant",
        "italian food": "italian_restaurant",
        "italian restaurant": "italian_restaurant",
        "japanese food": "japanese_restaurant",
        "japanese restaurant": "japanese_restaurant",
        "juice bar": "juice_shop",
        "landmark": "historical_landmark",
        "landscaping": "general_contractor",
        "laundry": "laundry",
        "law enforcement": "police",
        "library": "library",
        "liquor": "liquor_store",
        "lodging": "lodging",
        "lounge": "lounge_bar",
        "mac": "atm",
        "mall": "shopping_mall",
        "marina": "marina",
        "market": "market",
        "marketing": "marketing_consultant",
        "marketplace": "market",
        "massage": "massage",
        "mediterranean food": "mediterranean_restaurant",
        "mediterranean restaurant": "mediterranean_restaurant",
        "mexican food": "mexican_restaurant",
        "mexican restaurant": "mexican_restaurant",
        "middle eastern food": "middle_eastern_restaurant",
        "middle eastern restaurant": "middle_eastern_restaurant",
        "minibank": "atm",
        "minimart": "convenience_store",
        "mobile phone": "cell_phone_store",
        "monument": "monument",
        "mosque": "mosque",
        "motel": "motel",
        "mountain": "mountain_peak",
        "museum": "museum",
        "music": "live_music_venue",
        "muslim": "mosque",
        "new american food": "american_restaurant",
        "new american restaurant": "american_restaurant",
        "ngo": "non_profit_organization",
        "nightclub": "night_club",
        "non profit": "non_profit_organization",
        "non-profit": "non_profit_organization",
        "nonprofit": "non_profit_organization",
        "noodles": "noodle_shop",
        "not for profit": "non_profit_organization",
        "office": "corporate_office",
        "optometrist": "doctor",
        "organic grocery": "health_food_store",
        "outdoors": "tourist_attraction",
        "outlet shop": "discount_store",
        "outlet store": "discount_store",
        "park": "park",
        "parking": "parking",
        "parking lot": "parking",
        "peak": "mountain_peak",
        "pet store": "pet_store",
        "pharmacy": "pharmacy",
        "phone repair": "cell_phone_store",
        "photo": "store",
        "photo lab": "store",
        "photography lab": "store",
        "physician": "doctor",
        "pizza": "pizza_restaurant",
        "place of worship": "place_of_worship",
        "playground": "playground",
        "police station": "police",
        "port": "ferry_terminal",
        "post office": "post_office",
        "pub": "pub",
        "public artwork": "sculpture",
        "rail station": "train_station",
        "ramen": "ramen_restaurant",
        "religion": "place_of_worship",
        "religious": "place_of_worship",
        "resort": "resort_hotel",
        "restaurant": "restaurant",
        "salad": "salad_shop",
        "sandwich": "sandwich_shop",
        "scenic": "scenic_spot",
        "school": "school",
        "science museum": "museum",
        "seafood": "seafood_restaurant",
        "seafood restaurant": "seafood_restaurant",
        "second hand": "thrift_store",
        "second-hand": "thrift_store",
        "shopping center": "shopping_mall",
        "shopping mall": "shopping_mall",
        "show venue": "event_venue",
        "ski": "ski_resort",
        "smoke shop": "store",
        "snack": "snack_bar",
        "soba": "noodle_shop",
        "southern soul food": "soul_food_restaurant",
        "southern soul food restaurant": "soul_food_restaurant",
        "spa": "spa",
        "spirit": "liquor_store",
        "sporting": "sporting_goods_store",
        "sporting goods": "sporting_goods_store",
        "sports bar": "sports_bar",
        "sports store": "sporting_goods_store",
        "stadium": "stadium",
        "state park": "state_park",
        "stationery": "store",
        "supermarket": "supermarket",
        "surf": "beach",
        "surfing beach": "beach",
        "sushi": "sushi_restaurant",
        "sushi restaurant": "sushi_restaurant",
        "sweets": "candy_store",
        "swimming pool": "swimming_pool",
        "szechuan food": "chinese_restaurant",
        "szechuan restaurant": "chinese_restaurant",
        "taco": "taco_restaurant",
        "taxi": "taxi_stand",
        "taxi stand": "taxi_stand",
        "tea": "tea_house",
        "tea house": "tea_house",
        "temple": "place_of_worship",
        "thai food": "thai_restaurant",
        "thai restaurant": "thai_restaurant",
        "theater": "performing_arts_theater",
        "theatre": "performing_arts_theater",
        "thrift": "thrift_store",
        "tourist information": "visitor_center",
        "trailhead": "hiking_area",
        "train station": "train_station",
        "travel lounge": "airport",
        "truck rental": "car_rental",
        "turkish food": "turkish_restaurant",
        "turkish restaurant": "turkish_restaurant",
        "university": "university",
        "variety shop": "store",
        "vegan": "vegan_restaurant",
        "vegan food": "vegan_restaurant",
        "vegan restaurant": "vegan_restaurant",
        "vegetarian": "vegetarian_restaurant",
        "vegetarian food": "vegetarian_restaurant",
        "vegetarian restaurant": "vegetarian_restaurant",
        "vietnamese food": "vietnamese_restaurant",
        "vietnamese restaurant": "vietnamese_restaurant",
        "viewpoint": "scenic_spot",
        "vintage": "thrift_store",
        "waterfall": "scenic_spot",
        "wine": "liquor_store",
        "wine bar": "wine_bar",
        "zoo": "zoo",
    ]
}
