//
//  PlaceCategory+Mapbox.swift
//  LocoKit2
//
//  Created by Claude on 2026-08-10
//
//  GENERATED FILE — regenerate via Scripts/placecategory/generate_placecategory.py
//  (BIG-513). Mapbox category strings are compound comma-separated keyword
//  bundles (e.g. "hotel, motel, tourism, lodging"), not a clean taxonomy —
//  so resolution is keyword matching: first recognised token wins, tokens
//  checked in string order (Mapbox leads with the most specific term).
//  Pure history rescue: AT4 never fetches from Mapbox, so mapboxCategory
//  only exists on places migrated from AT3's Mapbox era. Table authored
//  against the observed vocabulary of a real mature DB and validated
//  against the PlaceCategory taxonomy at generation time; unmatched
//  strings resolve to nil, deliberately.
//

extension PlaceCategory {

    init?(mapboxCategory: String) {
        for token in mapboxCategory.components(separatedBy: ",") {
            let trimmed = token.trimmingCharacters(in: .whitespaces)
            if let raw = Self.mapboxKeywordMap[trimmed], let category = PlaceCategory(rawValue: raw) {
                self = category
                return
            }
        }
        return nil
    }

    static let mapboxKeywordMap: [String: String] = [
        "airport": "airport",
        "airport lounge": "airport",
        "airport services": "airport",
        "airport shop": "airport",
        "apparel": "clothing_store",
        "aquarium": "aquarium",
        "attraction": "tourist_attraction",
        "bakery": "bakery",
        "bank": "bank",
        "bar": "bar",
        "barber": "barber_shop",
        "baseball": "athletic_field",
        "baseball field": "athletic_field",
        "beach": "beach",
        "bed and breakfast": "bed_and_breakfast",
        "bodega": "convenience_store",
        "book shop": "book_store",
        "bookstore": "book_store",
        "botanical garden": "botanical_garden",
        "bridge": "historical_landmark",
        "buddhism": "buddhist_temple",
        "buddhist": "buddhist_temple",
        "bus station": "bus_station",
        "bus stop": "bus_stop",
        "business": "corporate_office",
        "cafe": "cafe",
        "campground": "campground",
        "camping": "campground",
        "cellphone": "cell_phone_store",
        "cemetery": "cemetery",
        "chair ski lift": "ski_resort",
        "church": "church",
        "clinic": "medical_clinic",
        "clothing": "clothing_store",
        "cocktail bar": "bar",
        "coffee": "coffee_shop",
        "computer": "electronics_store",
        "contractor": "general_contractor",
        "convenience": "convenience_store",
        "convenience store": "convenience_store",
        "corner store": "convenience_store",
        "dentist": "dentist",
        "department store": "department_store",
        "discount store": "discount_store",
        "donut": "donut_shop",
        "electronic": "electronics_store",
        "electronics": "electronics_store",
        "embassy": "embassy",
        "farmers market": "farmers_market",
        "fast food": "fast_food_restaurant",
        "ferry": "ferry_terminal",
        "finance": "bank",
        "fitness center": "fitness_center",
        "florist": "florist",
        "food court": "food_court",
        "french restaurant": "french_restaurant",
        "fried chicken": "fast_food_restaurant",
        "fuel": "gas_station",
        "garden": "garden",
        "gas station": "gas_station",
        "gift": "gift_shop",
        "government agency": "government_office",
        "graveyard": "cemetery",
        "groceries": "grocery_store",
        "grocery": "grocery_store",
        "gym": "gym",
        "hair": "hair_salon",
        "hardware": "hardware_store",
        "hike": "hiking_area",
        "hiking": "hiking_area",
        "hiking trailhead": "hiking_area",
        "historic": "historical_landmark",
        "historic site": "historical_landmark",
        "history museum": "history_museum",
        "hospital": "hospital",
        "hostel": "hostel",
        "hotel": "hotel",
        "hotel resort": "resort_hotel",
        "ice cream": "ice_cream_shop",
        "indian restaurant": "indian_restaurant",
        "islam": "mosque",
        "landmark": "historical_landmark",
        "landscaping": "general_contractor",
        "laundry": "laundry",
        "law enforcement": "police",
        "library": "library",
        "liquor": "liquor_store",
        "lodging": "lodging",
        "mall": "shopping_mall",
        "marina": "marina",
        "market": "market",
        "marketplace": "market",
        "massage": "massage",
        "minimart": "convenience_store",
        "mobile phone": "cell_phone_store",
        "monument": "monument",
        "mosque": "mosque",
        "motel": "motel",
        "museum": "museum",
        "muslim": "mosque",
        "nightclub": "night_club",
        "outdoors": "tourist_attraction",
        "park": "park",
        "parking": "parking",
        "parking lot": "parking",
        "pet store": "pet_store",
        "pharmacy": "pharmacy",
        "phone repair": "cell_phone_store",
        "pizza": "pizza_restaurant",
        "place of worship": "place_of_worship",
        "playground": "playground",
        "police station": "police",
        "port": "ferry_terminal",
        "post office": "post_office",
        "pub": "pub",
        "rail station": "train_station",
        "religion": "place_of_worship",
        "religious": "place_of_worship",
        "resort": "resort_hotel",
        "restaurant": "restaurant",
        "scenic": "scenic_spot",
        "school": "school",
        "science museum": "museum",
        "shopping center": "shopping_mall",
        "shopping mall": "shopping_mall",
        "ski": "ski_resort",
        "smoke shop": "store",
        "snack": "fast_food_restaurant",
        "spa": "spa",
        "sporting": "sporting_goods_store",
        "sporting goods": "sporting_goods_store",
        "sports store": "sporting_goods_store",
        "stadium": "stadium",
        "stationery": "store",
        "supermarket": "supermarket",
        "surf": "beach",
        "surfing beach": "beach",
        "swimming pool": "swimming_pool",
        "taxi": "taxi_stand",
        "taxi stand": "taxi_stand",
        "tea": "tea_house",
        "tea house": "tea_house",
        "temple": "place_of_worship",
        "thai restaurant": "thai_restaurant",
        "tourist information": "visitor_center",
        "trailhead": "hiking_area",
        "train station": "train_station",
        "university": "university",
        "variety shop": "store",
        "viewpoint": "scenic_spot",
        "waterfall": "scenic_spot",
        "zoo": "zoo",
    ]
}
